# Generated by Django 2.0.6 on 2018-06-21 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 21, 17, 40, 15, 599199, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
