# Generated by Django 2.0.6 on 2018-06-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0002_motor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motor',
            old_name='vehical_number',
            new_name='vehicle_number',
        ),
    ]
